import 'package:flutter/material.dart';
import 'package:flutter_html/flutter_html.dart';
import 'package:MyMedTrip/components/CustomAppBar.dart';
import 'package:get/get.dart';

class AboutApp extends StatelessWidget {
  const AboutApp({super.key});
  static const htmlData = """<div class="entry-content">
<p>Terms of Use<br>Effective Date: March 11, 2022</p>
<p><br>Welcome to the MyMedTrip website! MyMedTrip maintains this website (“Website”) for your<br>personal information, education and communication. Your access to and use of this Website is<br>subject to the following Terms of Use. Please read these Terms of Use carefully before<br>accessing or using the Website, so that you fully understand your rights and responsibilities.</p>
<p><br>IN THE EVENT OF A MEDICAL EMERGENCY, CONTACT YOUR LOCAL HOSPITAL OR DOCTOR. DO<br>NOT DISREGARD OR DELAY SEEKING MEDICAL ADVICE BECAUSE OF CONTENT YOU HAVE<br>READ ON THIS WEBSITE OR ADVICE OBTAINED THROUGH THIS WEBSITE. THIS WEBSITE DOES<br>NOT CONTAIN MEDICAL ADVICE AND WE DO NOT MONITOR THIS WEBSITE OR<br>COMMUNICATIONS FROM THIS WEBSITE FOR MEDICAL DIAGNOSTIC OR EMERGENCY HEALTH<br>CARE PURPOSES.</p>
<p><br>Your Agreement</p><p><br>ALL PAGES WITHIN THIS WEBSITE AND ANY INFORMATION, MATERIAL, CONTENT AND<br>SERVICES MADE AVAILABLE ON OR THROUGH THE WEBSITE ARE PROVIDED SUBJECT TO<br>YOUR AGREEMENT WITH THE TERMS AND CONDITIONS SET FORTH BELOW. PLEASE READ<br>THE FOLLOWING INFORMATION CAREFULLY. YOUR USE OF THIS WEBSITE WILL INDICATE<br>YOUR AGREEMENT TO THESE TERMS OF USE. IF YOU DO NOT AGREE TO THESE TERMS OF<br>USE, PROMPTLY EXIT THIS WEBSITE.</p>
<p><br>Should you choose to sign up or submit enquiry, your use of such web pages and services<br>provided may be subject to additional terms.</p>
<p><br>Changes to These Terms of Use</p>
<p><br>MyMedTrip reserves the right to modify or amend these Terms of Use at any time. All changes<br>will be effective immediately upon their posting. Material changes will be posted conspicuously<br>on the Website. By accessing the Website following posting of changes to the Terms of Use, you<br>agree to all such changes.</p><p><br>Your Representations</p>
<p><br>You represent and warrant that you are at least 18 years of age and that you possess the legal<br>right and ability to be legally bound by these Terms of Use. You agree to be responsible for your<br>use of the Website and to comply with your responsibilities and obligations as stated in these<br>Terms of Use.</p>
<p><br>If you are not 18 years of age, you are not permitted to use this Website and must exit now.<br>No Medical Advice</p>
<p><br>The information contained in this Website is presented for the purpose of educating consumers<br>on health and wellness topics and providing general information on MyMedTrip. NOTHING<br>CONTAINED IN THE WEBSITE IS INTENDED TO BE MEDICAL ADVICE FOR DIAGNOSIS OR<br>TREATMENT AND SHOULD NOT BE RELIED UPON AS YOUR PRIMARY SOURCE FOR HEALTH OR<br>MEDICAL INFORMATION.</p>
<p><br>THE INFORMATION SHOULD NOT BE CONSIDERED COMPLETE AND SHOULD NOT BE RELIED<br>ON TO SUGGEST A COURSE OF TREATMENT FOR A PARTICULAR INDIVIDUAL OR USED IN<br>PLACE OF A VISIT, CALL, CONSULTATION OR THE ADVICE OF YOUR PHYSICIAN OR OTHER<br>QUALIFIED HEALTH CARE PROVIDER. YOU SHOULD NEVER DISREGARD MEDICAL ADVICE OR<br>DELAY IN SEEKING IT BECAUSE OF SOMETHING YOU HAVE READ ON THE WEBSITE.<br>INFORMATION ON THIS WEBSITE IS INTENDED TO AUGMENT OTHER SOURCES OF<br>INFORMATION AND SHOULD NOT BE CONSIDERED A SUBSTITUTE FOR YOUR PERSONAL<br>RESPONSIBILITY AND DILIGENCE.</p>
<p><br>INFORMATION CONTAINED IN THE WEBSITE IS NOT EXHAUSTIVE AND DOES NOT COVER ALL<br>DISEASES, AILMENTS, PHYSICAL CONDITIONS OR THEIR TREATMENT. SHOULD YOU HAVE ANY<br>HEALTH CARE RELATED QUESTIONS, CALL OR SEE YOUR PHYSICIAN OR OTHER QUALIFIED<br>HEALTH CARE PROVIDER PROMPTLY, OR CONTACT YOUR LOCAL EMERGENCY SERVICES IN<br>CASE OF AN EMERGENCY. ALWAYS CONSULT WITH YOUR PHYSICIAN OR OTHER QUALIFIED<br>HEALTH CARE PROVIDER WITH YOUR HEALTH CARE RELATED QUESTIONS, OR BEFORE<br>EMBARKING ON A NEW TREATMENT, DIET OR FITNESS PROGRAM.</p>
<p><br>Website Content</p>
<p><br>Although MyMedTrip attempts to ensure the integrity and accuracy of the content on the<br>Website, it makes no guarantees whatsoever as to the correctness or accuracy of such content.<br>It is possible that the Website and its content could include inaccuracies or errors (human or<br>machine), and third parties could make unauthorized additions, deletions and alterations to the<br>Website. In the event you become aware of an inaccuracy, please inform MyMedTrip<br>(hi@mymedtrip.com) so that it can be corrected.</p>
<p><br>MyMedTrip DOES NOT MAKE ANY WARRANTY AS TO THE RELIABILITY, ACCURACY,<br>TIMELINESS, USEFULNESS, ADEQUACY, COMPLETENESS OR SUITABILITY OF THE WEBSITE OR<br>ANY CONTENT OR INFORMATION CONTAINED WITHIN IT.</p>
<p><br>The Website content may contain health or medical related materials that you find sexually<br>explicit or otherwise offensive. MyMedTrip accepts no responsibility for such materials. Use of<br>the Website is at your own risk.</p>
<p><br>You may choose to use other services provided by third parties in conjunction with your access<br>to and use of this Website. Such services may include, but are not limited to, translation services,<br>location services, and other third-party offerings. Any links to such services are provided for your<br>convenience only. MyMedTrip has no control over the contents of these services, and MyMedTrip<br>accepts no responsibility for them or for any loss or damage that may arise from your use of<br>them. Such services may require you to submit your information to a third party, which may result<br>in a copy of your information being used and/or stored by a third party. If you decide to access<br>any such services in conjunction with your access to and use of this Website, you do so entirely<br>at your own risk and subject to the terms and conditions of use for such services.</p>
<p><br>Website content may be changed or updated without notice. MyMedTrip reserves the right to<br>modify Website content without any obligation to notify past, current or prospective Website<br>users.</p>
<p><br>MyMedTrip makes no representations that the materials on this Website are appropriate or<br>available for use in all countries. Those who do access this Website from other states or<br>countries are solely responsible for compliance with the laws of such state or country.<br>You are responsible for the accuracy of information that you submit to us via this Website. We<br>have no obligation or liability for any information that is not accurate.<br>Restrictions on Your Use</p>
<p><br>You may view material from the Website for your own personal use or the internal use of your<br>business. You may not download, reproduce or otherwise distribute any materials on this<br>Website without our prior express written consent and/or the consent of any third party copyright<br>owner.</p>
<p><br>Any rights that are not expressly granted by these Terms of Use or any applicable end user<br>license agreements are reserved by MyMedTrip.<br>You may not use this Website or its content for any purpose prohibited or restricted by law or in<br>violation of these Terms of Use.</p>
<p><br>Intellectual Property Rights<br>The Website and its content is the property of MyMedTrip, its affiliates or its third party sources<br>and vendors.</p>
<p><br>No Warranty<br>MyMedTrip CANNOT AND DOES NOT WARRANT AGAINST HUMAN AND MACHINE ERRORS,<br>OMISSIONS, DELAYS, INTERRUPTIONS OR LOSSES, INCLUDING LOSS OF DATA. MyMedTrip<br>CANNOT AND DOES NOT GUARANTEE OR WARRANT THAT THIS WEBSITE WILL BE FREE OF<br>INFECTION BY VIRUSES, WORMS, TROJAN HORSES OR OTHER MALICIOUS CODE. MyMedTrip<br>DOES NOT WARRANT OR GUARANTEE THAT THE FUNCTIONS OR SERVICES PERFORMED IN<br>THE WEB SITE WILL BE UNINTERRUPTED OR ERROR-FREE OR THAT DEFECTS IN THE WEBSITE<br>WILL BE CORRECTED.</p>
<p><br>THIS WEBSITE IS PROVIDED “AS IS,” WITH ALL FAULTS, WITH NO REPRESENTATIONS OR<br>WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, AND DISCLAIMS ALL SUCH<br>WARRANTIES INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF<br>MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON INFRINGEMENT<br>AND ALL WARRANTIES ARISING FROM A COURSE OF DEALING OR USAGE IN TRADE.</p>
<p><br>MyMedTrip MAKES NO WARRANTY OR REPRESENTATION REGARDING THE RESULTS THAT<br>MAY BE OBTAINED FROM USE OF THIS WEBSITE, OR USE OF MATERIAL, INFORMATION OR<br>DATA DOWNLOADED OR OTHERWISE OBTAINED FROM THIS WEBSITE, OR REGARDING THE<br>ACCURACY OR RELIABILITY OF ANY INFORMATION OBTAINED FROM THIS WEBSITE.<br>MyMedTrip DOES NOT HAVE ANY RESPONSIBILITY FOR THE TIMELINESS, DELETION,<br>MISDELIVERY OR FAILURE TO STORE ANY USER COMMUNICATION.<br>YOU ASSUME TOTAL RESPONSIBILITY AND RISK FOR YOUR ACCESS OR USE OF THE INTERNET<br>AND THIS WEBSITE. </p>
<p>You acknowledge and agree (1) that your use of this Website and any<br>material, information or data downloaded or otherwise obtained through the use of this Website<br>is at your own discretion and risk, and (2) that you are solely responsible for any damage to your<br>computer system for loss of data that results from the download of such material, information or<br>data, and for any other form of damage that may be incurred.</p>
<p><br>No advice or information, whether oral or written, obtained by you from MyMedTrip or in any<br>other manner from this Website creates any warranty.</p>
<p><br>Limitation of Liability</p>
<p><br>NEITHER MyMedTrip, ITS AFFILIATES, NOR THEIR RESPECTIVE OFFICERS, DIRECTORS,<br>EMPLOYEES OR AGENTS ARE RESPONSIBLE OR LIABLE TO YOU UNDER ANY THEORY OF<br>LIABILITY OR INDEMNITY IN CONNECTION WITH YOUR ACCESS OR USE OF THE WEBSITE OR<br>ANY OF ITS CONTENT OR SERVICES.</p>
<p><br>FURTHERMORE, NEITHER MyMedTrip, ITS AFFILIATES, NOR THEIR RESPECTIVE OFFICERS,<br>DIRECTORS, EMPLOYEES OR AGENTS ARE OR WILL BE LIABLE OR RESPONSIBLE FOR ANY<br>DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, PUNITIVE, OR OTHER<br>DAMAGES OF ANY KIND ARISING OUT OF OR RELATING IN ANY WAY TO THE WEBSITE AND/OR<br>ANY CONTENT ON THE WEBSITE, WHETHER SUCH DAMAGES ARE BASED IN TORT, CONTRACT,<br>ERROR (HUMAN OR MACHINE), NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, EVEN IF<br>MyMedTrip HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. YOUR SOLE REMEDY<br>FOR DISSATISFACTION WITH THE SITE AND/OR ANY DAMAGE RESULTING FROM THE SITE IS<br>TO STOP USING THE SITE, EVEN IF SUCH REMEDY SHOULD FAIL OF ITS ESSENTIAL PURPOSE.<br>WE USE REASONABLE EFFORT TO CHECK THE ACCURACY OR ERROR OF THE INFORMATIN ON<br>OUR WEBSITE, IDENTIFIED BY US OR BROUGHT TO OUR KNOWLEDGE.</p>
<p><br>YOU SHOULD, HOWEVER NOTE THAT WE DO NOT WARRANT SUCH INFORMATION WILL BE<br>ERROR FREE.</p>
<p><br>Indemnification</p>
<p><br>You agree to indemnify, defend and hold harmless MyMedTrip, its affiliates and their respective<br>officers, directors, employees and agents from and against all losses, expenses, liabilities,<br>damages and costs, including without limitation reasonable legal fees, resulting from or arising<br>from any use of the Website or its content or any violation of these Terms of Use.</p>
<p><br>Third-Party Sites</p>
<p><br>MyMedTrip has no liability for any third party website that you may access through this Website.<br>When you access a third party website, please understand that it is independent from<br>MyMedTrip, and that MyMedTrip has no control over the Website or its content.<br>In addition, MyMedTrip does not endorse any third party whose Website may be linked from this<br>Website. MyMedTrip does not and cannot ensure that the propriety, security or accuracy of any<br>third party website and we encourage you to review the posted policies of any website that you<br>visit.</p>
<p><br>Disputes, Choice of Law &amp; Venue</p>
<p><br>These Website Terms of Use are a binding agreement between you and MyMedTrip.<br>In any action to enforce these Website Terms of Use, MyMedTrip will be entitled to all costs and<br>legal fees it incurs.</p>
<p><br>Any cause of action or claim you have regarding the Website must be commenced within one<br>year after the claim or cause of action arises or the claim or cause of action is barred.</p>
</div>""";
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: CustomAppBar(
        pageName: "Terms of usage".tr,
        showDivider: true,
      ),
      body: SafeArea(
          child: SingleChildScrollView(
        child: SizedBox(
          child: Html(data: htmlData),
        ),
      )),
    );
  }
}
