name: MyMedTrip
version: 1.0.2+21
publish_to: noney
description: Amazon of medical tourism
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  adaptive_action_sheet: ^2.0.2
  lottie: ^2.2.0
  get_storage: ^2.1.1
  path_provider:
  path_provider_android: ^2.2.1
  path_provider_ios: 2.0.11
  connectivity_plus: ^5.0.2
  animated_text_kit: 4.2.2
  slide_to_confirm: 1.1.0
  camera: any
  path: any
  file_picker: ^6.1.1
  url_launcher: ^6.2.1
  flutter_svg: ^2.0.9
  flutter: 
    sdk: flutter
  firebase_core: ^2.7.1
  pattern_formatter: ^3.0.0
  intl_phone_field: ^3.1.0
  razorpay_flutter: ^1.3.4
  agora_rtc_engine: ^6.1.0
  permission_handler: ^11.0.1
  firebase_crashlytics: ^3.1.0
  logger: ^2.0.2+1
  flutter_html: ^3.0.0-alpha.6
  intl: ^0.18.1
  firebase_auth: ^4.5.0
  firebase_database: ^10.1.2
  firebase_messaging: ^14.5.0
  firebase_storage: ^11.1.2
  shimmer: ^3.0.0
  local_auth: ^2.1.6
  image_picker: ^1.0.4
  flutter_launcher_icons: ^0.13.1
  cached_network_image:
  flutter_local_notifications: ^16.2.0
  select_dialog: ^2.0.0
  flutter_callkit_incoming: ^2.0.0+2
  flutter_pdfview: ^1.2.7
  flutter_file_downloader: ^1.1.2
  wakelock_plus: ^1.1.1
  proximity_sensor: ^1.0.4
  dio: ^5.3.2
  syncfusion_flutter_pdfviewer: ^20.4.54
  flutter_tawk: ^0.1.0
  webview_flutter: ^3.0.4
  app_tracking_transparency: ^2.0.4
  uuid: ^3.0.7
  agora_uikit: ^1.3.7
  youtube_player_flutter: ^8.1.2

dev_dependencies: 
  dart_code_metrics: ^5.7.2
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - Images/mr.png
    - Images/PR.png
    - Images/Is.png
    - Images/VD.png
    - Images/WD.png
    - Images/hos.png
    - Images/hos1.jpg
    - Images/doc.png
    - Images/men.jpg
    - Images/P1.jpg
    - Images/P2.jpg
    - Images/blog.png
    - Images/St.png
    - Images/Tr.png
    - Images/Md.png
    - Images/dollar.png
    - Images/rrr.png
    - Images/ps.jpg
    - Images/CH.png
    - Images/load.jpg
    - Images/avatar-placeholder.jpeg
    - Images/placeholder.png
    - assets/
    - assets/lottie/
    - assets/icons/
    - shorebird.yaml
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/UrbanistRomanBold.ttf
          weight: 700
        - asset: assets/fonts/UrbanistSemiBold.ttf
          weight: 600
        - asset: assets/fonts/UrbanistRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/UrbanistRegular.ttf
          weight: 400
        - asset: assets/fonts/UrbanistRomanBlack.ttf
          weight: 900
    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/SourceSansProSemiBold.ttf
          weight: 600
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/playstore.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/playstore.png"
    background_color: "#ffffff"
    theme_color: "#0e3f84"

