name: mmt_
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  adaptive_action_sheet: ^2.0.2
  lottie: ^2.2.0
  get_storage: 2.0.3
  path_provider_android: 2.0.22
  path_provider_ios: 2.0.11
  connectivity_plus: ^3.0.3
  animated_text_kit: 4.2.2
  slide_to_confirm: 1.1.0
  camera: any
  path: any
  file_picker: ^5.2.5
  url_launcher: 6.1.10
  flutter_svg: 2.0.3
  flutter: 
    sdk: flutter
  firebase_core: ^2.7.1
  pattern_formatter: ^2.0.0
  intl_phone_field: ^3.1.0
  razorpay_flutter: ^1.3.4
  agora_rtc_engine: ^6.1.0
  permission_handler: ^9.2.0
  firebase_crashlytics: ^3.1.0
  logger: ^1.3.0
  flutter_html: ^3.0.0-alpha.6
  intl: ^0.17.0
  firebase_auth: ^4.5.0
  firebase_database: ^10.1.2
  firebase_messaging: ^14.5.0
  flutter_file_view: ^2.2.1
  firebase_storage: ^11.1.2
  shimmer: ^2.0.0
  youtube_player_flutter: ^8.1.2
  local_auth: ^2.1.6
  image_picker: ^0.8.7+5

dev_dependencies: 
  dart_code_metrics: ^5.7.2
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - Images/mr.png
    - Images/PR.png
    - Images/Is.png
    - Images/VD.png
    - Images/WD.png
    - Images/hos.png
    - Images/hos1.jpg
    - Images/doc.png
    - Images/men.jpg
    - Images/P1.jpg
    - Images/P2.jpg
    - Images/blog.png
    - Images/St.png
    - Images/Tr.png
    - Images/Md.png
    - Images/dollar.png
    - Images/rrr.png
    - Images/ps.jpg
    - Images/CH.png
    - Images/load.jpg
    - Images/avatar-placeholder.jpeg
    - assets/
    - assets/lottie/
    - assets/icons/
  fonts: 
    - family: Brandon
      fonts: 
        - asset: fonts/BrandonText-Bold.ttf
    - family: BrandonReg
      fonts: 
        - asset: fonts/BrandonText-Regular.otf
    - family: BrandonMed
      fonts: 
        - asset: fonts/BrandonText-Medium.otf
  uses-material-design: true

