// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3zpdPFZHof19ydzy6XYqSYEoafYvKIi8',
    appId: '1:922681658193:web:0c19c89833e51c376aa170',
    messagingSenderId: '922681658193',
    projectId: 'mymedtrip-app',
    authDomain: 'mymedtrip-app.firebaseapp.com',
    databaseURL: 'https://mymedtrip-app-default-rtdb.firebaseio.com',
    storageBucket: 'mymedtrip-app.appspot.com',
    measurementId: 'G-ELKMH046XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwa0paL-G-HEGoi7k3OYgOK9wpPgD_nlg',
    appId: '1:922681658193:android:588e3e7c8aab646d6aa170',
    messagingSenderId: '922681658193',
    projectId: 'mymedtrip-app',
    databaseURL: 'https://mymedtrip-app-default-rtdb.firebaseio.com',
    storageBucket: 'mymedtrip-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASWXIHAXY3_pVZntIq7XQcR2IDSKlEihM',
    appId: '1:922681658193:ios:ceef44b3da9aa9e86aa170',
    messagingSenderId: '922681658193',
    projectId: 'mymedtrip-app',
    databaseURL: 'https://mymedtrip-app-default-rtdb.firebaseio.com',
    storageBucket: 'mymedtrip-app.appspot.com',
    iosClientId: '922681658193-fhui2l8k8lunrj57a7epknoal0q6th87.apps.googleusercontent.com',
    iosBundleId: 'com.example.mmt',
  );
}
